---
docker:
  gpg_key: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
  keyring: "/usr/share/keyrings/docker-archive-keyring.gpg"
  source_file: "/etc/apt/sources.list.d/docker.list"
  apt_list:
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
  packages:
    - docker-ce
    - docker-ce-cli
    - containerd.io

docker_compose:
  url: "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64"
  bin: "/usr/local/bin/docker-compose"

ufw:
  service:
    state: "stopped"
    enabled: "no"

system_user: "{{ ansible_user }}"
project_dir: /home/{{ system_user }}/project-wordpress

wp:
  image: "wordpress:fpm-alpine"
  dirs:
    - wordpress
    - db-data
    - nginx
    - logs/nginx
  db_image: mysql:latest
  db_name: wordpress
  db_user: wp_user
  db_host: db

#  db_psw: supersecret


nginx:
  image: nginx:alpine
